# Generated by Django 4.2.5 on 2023-10-04 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_a_pic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='get_a_pic_app.image')),
                ('thumbnail_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='get_a_pic_app.thumbnailsize')),
            ],
        ),
    ]
